#### INSERT CLIENT ID AND SECRET HERE ###
SPOTIPY_CLIENT_ID = 'YOUR CLIENT ID HERE'
SPOTIPY_CLIENT_SECRET = 'YOUR CLIENT SECRET HERE'


[theme]
base="dark"
primaryColor="#1DB954"
backgroundColor="#000000"
secondaryBackgroundColor="#121212"
textColor="#FFFFFF"